append-when-occupied = true
watch-config = true
remove-empty = true
renamers = ["classified", "client", "constant"]

[names]
constant = ""

[[names.classified]]
"" = ["Chromium"]

[[names.classified]]
"" = ["Firefox Developer Edition"]

[[names.classified]]
"" = ["Mate-terminal"]

[[names.classified]]
"" = ["Thunar"]

[[names.classified]]
"" = ["Xfce4-taskmanager"]

[[names.classified]]
"" = ["Mousepad"]

[[names.classified]]
"" = ["qutebrowser"]

[[names.classified]]
"" = ["Qalculate-gtk", "Gnome-calculator"]
